"""
Reminder Service — Phase 3D Communication Infrastructure.

Architecture:
  Reminders are DERIVED EVENTS generated by scheduled tasks.
  This service provides the functions that queue workers or schedulers call.

  IMPORTANT:
  - No cron hacks inside endpoint handlers.
  - Business endpoints emit events; reminder generation is a separate concern.
  - These functions are designed to be called by:
    * Background task schedulers (APScheduler, Celery Beat)
    * Queue workers (Celery, RQ, AWS SQS Lambda)
    * Manual trigger via admin endpoint

  TODO: Phase 4 — Queue worker integration (Celery / RQ / AWS SQS)
  TODO: Phase 4 — Retry with exponential backoff
  TODO: Phase 4 — Push notification support (Firebase / APNs)
  TODO: Phase 5 — Patient communication preferences / consent management
  TODO: Phase 5 — Opt-out / unsubscribe handling
  TODO: Phase 6 — AI-generated follow-up message content
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.crud import crud_notification
from app.models.appointment import Appointment, AppointmentStatus
from app.models.notification import (
    NotificationChannel,
    NotificationEvent,
    NotificationEventType,
)
from app.services.notification_service import (
    create_reminder_event,
    dispatch_notification,
)

logger = logging.getLogger(__name__)


# ═════════════════════════════════════════════════════════════════════════════
# Reminder Configuration
# ═════════════════════════════════════════════════════════════════════════════

# Default reminder timing (can be made tenant-configurable in future)
TWENTY_FOUR_HOUR_REMINDER = timedelta(hours=24)
TWO_HOUR_REMINDER = timedelta(hours=2)
FOLLOW_UP_REMINDER = timedelta(days=1)  # Day before follow-up

# Default channels for reminders
DEFAULT_REMINDER_CHANNELS = [NotificationChannel.email, NotificationChannel.sms]


# ═════════════════════════════════════════════════════════════════════════════
# Reminder Generation
# ═════════════════════════════════════════════════════════════════════════════


def generate_24_hour_reminders(
    db: Session,
    *,
    now: datetime | None = None,
    channels: list[NotificationChannel] | None = None,
) -> list[NotificationEvent]:
    """
    Generate 24-hour appointment reminders.

    Finds appointments scheduled ~24 hours from now and creates
    reminder notification events for them.

    Args:
        db: Database session.
        now: Current time (for testability). Defaults to UTC now.
        channels: Channels to dispatch through. Defaults to [email, sms].

    Returns:
        List of created notification events.
    """
    if now is None:
        now = datetime.now(timezone.utc)

    reminder_start = now + TWENTY_FOUR_HOUR_REMINDER - timedelta(minutes=30)
    reminder_end = now + TWENTY_FOUR_HOUR_REMINDER + timedelta(minutes=30)

    return _generate_reminders_for_window(
        db,
        reminder_start=reminder_start,
        reminder_end=reminder_end,
        event_type=NotificationEventType.appointment_reminder,
        channels=channels or DEFAULT_REMINDER_CHANNELS,
    )


def generate_2_hour_reminders(
    db: Session,
    *,
    now: datetime | None = None,
    channels: list[NotificationChannel] | None = None,
) -> list[NotificationEvent]:
    """
    Generate 2-hour appointment reminders.

    Finds appointments scheduled ~2 hours from now and creates
    reminder notification events for them.

    Args:
        db: Database session.
        now: Current time (for testability). Defaults to UTC now.
        channels: Channels to dispatch through. Defaults to [email, sms].

    Returns:
        List of created notification events.
    """
    if now is None:
        now = datetime.now(timezone.utc)

    reminder_start = now + TWO_HOUR_REMINDER - timedelta(minutes=15)
    reminder_end = now + TWO_HOUR_REMINDER + timedelta(minutes=15)

    return _generate_reminders_for_window(
        db,
        reminder_start=reminder_start,
        reminder_end=reminder_end,
        event_type=NotificationEventType.appointment_reminder,
        channels=channels or DEFAULT_REMINDER_CHANNELS,
    )


def generate_follow_up_reminders(
    db: Session,
    *,
    now: datetime | None = None,
    channels: list[NotificationChannel] | None = None,
) -> list[NotificationEvent]:
    """
    Generate follow-up appointment reminders.

    Finds appointments with follow_up_date set to tomorrow and creates
    reminder notification events.

    Args:
        db: Database session.
        now: Current time (for testability). Defaults to UTC now.
        channels: Channels to dispatch through. Defaults to [email, sms].

    Returns:
        List of created notification events.
    """
    if now is None:
        now = datetime.now(timezone.utc)

    reminder_start = now + FOLLOW_UP_REMINDER - timedelta(hours=6)
    reminder_end = now + FOLLOW_UP_REMINDER + timedelta(hours=6)

    # Find completed appointments with follow_up_date in the target window
    stmt = select(Appointment).where(
        Appointment.status == AppointmentStatus.completed,
        Appointment.follow_up_date.isnot(None),
        Appointment.follow_up_date >= reminder_start,
        Appointment.follow_up_date <= reminder_end,
        Appointment.is_deleted == False,
    )

    appointments = list(db.scalars(stmt).all())
    logger.info(
        "Found %d appointments with follow-up dates in window",
        len(appointments),
    )

    events: list[NotificationEvent] = []
    for appt in appointments:
        # Check if reminder already sent for this appointment
        existing = _check_existing_reminder(
            db, appt.id, NotificationEventType.follow_up_reminder
        )
        if existing:
            continue

        payload = {
            "patient_name": None,  # Resolved at render time
            "doctor_name": None,
            "follow_up_date": appt.follow_up_date.isoformat() if appt.follow_up_date else None,
            "appointment_time": appt.appointment_time.isoformat(),
        }

        event = create_reminder_event(
            db,
            tenant_id=appt.tenant_id,
            patient_id=appt.patient_id,
            doctor_id=appt.doctor_id,
            appointment_id=appt.id,
            event_type=NotificationEventType.follow_up_reminder,
            payload=payload,
        )
        events.append(event)

        # Dispatch immediately (future: queue-based)
        dispatch_notification(
            db,
            event.id,
            channels=channels or DEFAULT_REMINDER_CHANNELS,
        )

    db.flush()
    logger.info("Generated %d follow-up reminder events", len(events))
    return events


def _generate_reminders_for_window(
    db: Session,
    *,
    reminder_start: datetime,
    reminder_end: datetime,
    event_type: NotificationEventType,
    channels: list[NotificationChannel],
) -> list[NotificationEvent]:
    """
    Generate reminder events for appointments in a time window.

    Finds scheduled appointments whose appointment_time falls within
    the reminder window and creates notification events.

    Args:
        db: Database session.
        reminder_start: Start of the reminder window.
        reminder_end: End of the reminder window.
        event_type: Type of reminder event to create.
        channels: Channels to dispatch through.

    Returns:
        List of created notification events.
    """
    stmt = select(Appointment).where(
        Appointment.status == AppointmentStatus.scheduled,
        Appointment.appointment_time >= reminder_start,
        Appointment.appointment_time <= reminder_end,
        Appointment.is_deleted == False,
    )

    appointments = list(db.scalars(stmt).all())
    logger.info(
        "Found %d appointments in reminder window [%s, %s]",
        len(appointments),
        reminder_start.isoformat(),
        reminder_end.isoformat(),
    )

    events: list[NotificationEvent] = []
    for appt in appointments:
        # Check if reminder already sent for this appointment
        existing = _check_existing_reminder(db, appt.id, event_type)
        if existing:
            continue

        payload = {
            "patient_name": None,  # Resolved at render time from branding context
            "doctor_name": None,
            "appointment_time": appt.appointment_time.isoformat(),
        }

        event = create_reminder_event(
            db,
            tenant_id=appt.tenant_id,
            patient_id=appt.patient_id,
            doctor_id=appt.doctor_id,
            appointment_id=appt.id,
            event_type=event_type,
            payload=payload,
        )
        events.append(event)

        # Dispatch immediately (future: queue-based)
        dispatch_notification(
            db,
            event.id,
            channels=channels,
        )

    db.flush()
    logger.info("Generated %d reminder events", len(events))
    return events


def _check_existing_reminder(
    db: Session,
    appointment_id: UUID,
    event_type: NotificationEventType,
) -> bool:
    """
    Check if a reminder event already exists for this appointment.

    Prevents duplicate reminders from being generated.
    """
    stmt = select(NotificationEvent).where(
        NotificationEvent.appointment_id == appointment_id,
        NotificationEvent.event_type == event_type,
        NotificationEvent.is_deleted == False,
    )
    existing = db.scalar(stmt)
    return existing is not None


# ═════════════════════════════════════════════════════════════════════════════
# Batch Processing
# ═════════════════════════════════════════════════════════════════════════════


def process_all_reminders(
    db: Session,
    *,
    now: datetime | None = None,
) -> dict[str, int]:
    """
    Process all reminder types in a single call.

    Designed to be called by a scheduled task / cron job.

    Args:
        db: Database session.
        now: Current time (for testability).

    Returns:
        Dict with counts of reminders generated per type.
    """
    if now is None:
        now = datetime.now(timezone.utc)

    results: dict[str, int] = {}

    try:
        events = generate_24_hour_reminders(db, now=now)
        results["24_hour"] = len(events)
    except Exception as exc:
        logger.error("Failed to generate 24-hour reminders: %s", exc)
        results["24_hour"] = 0

    try:
        events = generate_2_hour_reminders(db, now=now)
        results["2_hour"] = len(events)
    except Exception as exc:
        logger.error("Failed to generate 2-hour reminders: %s", exc)
        results["2_hour"] = 0

    try:
        events = generate_follow_up_reminders(db, now=now)
        results["follow_up"] = len(events)
    except Exception as exc:
        logger.error("Failed to generate follow-up reminders: %s", exc)
        results["follow_up"] = 0

    db.commit()
    logger.info("Reminder processing complete: %s", results)
    return results


def process_pending_deliveries(
    db: Session,
    *,
    limit: int = 50,
) -> int:
    """
    Process pending deliveries that haven't been sent yet.

    Designed to be called by a queue worker.

    Args:
        db: Database session.
        limit: Maximum number of pending deliveries to process.

    Returns:
        Number of deliveries processed.
    """
    pending = crud_notification.get_pending_deliveries(db, limit=limit)
    processed = 0

    for delivery in pending:
        try:
            from app.services.notification_service import retry_failed_delivery

            success = retry_failed_delivery(db, delivery.id)
            if success:
                processed += 1
        except Exception as exc:
            logger.error(
                "Failed to process pending delivery %s: %s",
                delivery.id,
                exc,
            )

    if processed > 0:
        db.commit()

    logger.info("Processed %d / %d pending deliveries", processed, len(pending))
    return processed
