"""Add Phase 2 fields: follow_up_date, follow_up_notes, appointment_vitals, prescriptions, prescription_items

Revision ID: 0fe071b8e03e
Revises: adfef084535d
Create Date: 2026-05-10 12:58:00.669777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe071b8e03e'
down_revision: Union[str, None] = 'adfef084535d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_vitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_appointment_vitals_appointment')
    )
    op.create_index('ix_appointment_vitals_appointment', 'appointment_vitals', ['appointment_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescriptions_appointment', 'prescriptions', ['appointment_id'], unique=False)
    op.create_index('ix_prescriptions_patient', 'prescriptions', ['patient_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescription_items_prescription', 'prescription_items', ['prescription_id'], unique=False)
    op.add_column('appointments', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'follow_up_notes')
    op.drop_column('appointments', 'follow_up_date')
    op.drop_index('ix_prescription_items_prescription', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('ix_prescriptions_appointment', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_appointment_vitals_appointment', table_name='appointment_vitals')
    op.drop_table('appointment_vitals')
    # ### end Alembic commands ###
