"""add_clinical_notes_to_appointments

Revision ID: 5a93cca8f072
Revises: n9o0p1q2r3s4
Create Date: 2026-05-08 20:46:16.416168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a93cca8f072'
down_revision: Union[str, None] = 'n9o0p1q2r3s4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_completion_idempotency'), table_name='appointment_completion_idempotency')
    op.create_unique_constraint('uq_completion_idempotency', 'appointment_completion_idempotency', ['appointment_id', 'idempotency_key'])
    op.add_column('appointments', sa.Column('clinical_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('treatment_summary', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_appointments_tenant'), table_name='appointments')
    op.drop_index(op.f('idx_billings_tenant'), table_name='billings')
    op.drop_index(op.f('ix_doctor_profiles_doctor_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_pending_partial'), table_name='doctor_profiles', postgresql_where="((verification_status)::text = 'pending'::text)")
    op.create_index('idx_doctor_profiles_verification_status', 'doctor_profiles', ['verification_status'], unique=False)
    op.create_index('idx_doctors_tenant_active_listing', 'doctors', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_inventory_movements_reference'), table_name='inventory_movements')
    op.drop_index(op.f('idx_patients_tenant'), table_name='patients')
    op.drop_index(op.f('ux_users_email_ci'), table_name='users')
    op.drop_index(op.f('ux_users_one_admin_per_tenant'), table_name='users', postgresql_where="((role = 'admin'::userrole) AND (tenant_id IS NOT NULL))")
    op.create_index('ux_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_users_email_lower', table_name='users')
    op.create_index(op.f('ux_users_one_admin_per_tenant'), 'users', ['tenant_id'], unique=True, postgresql_where="((role = 'admin'::userrole) AND (tenant_id IS NOT NULL))")
    op.create_index(op.f('ux_users_email_ci'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_patients_tenant'), 'patients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference'), 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.drop_index('idx_doctors_tenant_active_listing', table_name='doctors')
    op.drop_index('idx_doctor_profiles_verification_status', table_name='doctor_profiles')
    op.create_index(op.f('ix_doctor_profiles_pending_partial'), 'doctor_profiles', ['verification_status'], unique=False, postgresql_where="((verification_status)::text = 'pending'::text)")
    op.create_index(op.f('ix_doctor_profiles_doctor_id'), 'doctor_profiles', ['doctor_id'], unique=True)
    op.create_index(op.f('idx_billings_tenant'), 'billings', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_appointments_tenant'), 'appointments', ['tenant_id'], unique=False)
    op.drop_column('appointments', 'treatment_summary')
    op.drop_column('appointments', 'diagnosis')
    op.drop_column('appointments', 'clinical_notes')
    op.drop_constraint('uq_completion_idempotency', 'appointment_completion_idempotency', type_='unique')
    op.create_index(op.f('uq_completion_idempotency'), 'appointment_completion_idempotency', ['appointment_id', 'idempotency_key'], unique=True)
    # ### end Alembic commands ###
