export {
  loginSchema,
  patientSchema,
  appointmentSchema,
  billingSchema,
  doctorSchema,
  patientSignupSchema,
  doctorSignupSchema,
  hospitalSignupSchema,
  resetPasswordSchema,
  completeStructuredDoctorProfileSchema,
  type LoginFormData,
  type PatientFormData,
  type PatientFormInput,
  type AppointmentFormData,
  type AppointmentFormInput,
  type BillingFormData,
  type BillingFormInput,
  type DoctorFormData,
  type DoctorFormInput,
  type PatientSignupFormData,
  type PatientSignupFormInput,
  type DoctorSignupFormData,
  type DoctorSignupFormInput,
  type HospitalSignupFormData,
  type HospitalSignupFormInput,
  type ResetPasswordFormData,
  type CompleteStructuredDoctorProfileFormData,
  type CompleteStructuredDoctorProfileFormInput,
} from './schemas';
